all:
  vars:
    ansible_ssh_private_key_file: "../../SSH/sisyphe_key"
    ansible_user: sisyphe # Or your specific user
    ansible_become: yes

  children:
    dns:
      hosts:
        10.0.1.2:
    # K3s Cluster (Management/Rancher)
    k3s_cluster:
      hosts:
        10.0.1.3:

    # RKE2 Cluster (Workloads)
    rke2_cluster:
      children:
        workers:
          children:
              worker1:
                hosts:
                  10.0.1.5:
              worker2:
                hosts:
                  10.0.1.6:
        master:
          hosts:
            10.0.1.4: