---
# - name: "Setup DNS"
#   import_playbook: "dns/main.yml"
# - name: "Setup k3s cluster"
#   import_playbook: "k3s_rancher/main.yml"
- name: "Setup nodes"
  import_playbook: "rke2_cluster/main.yml"