---
- name: "Setup DNS"
  import_playbook: "dns/main.yml"
- name: "Setup k3s cluster"
  import_playbook: "dashboard/main.yml"
- name: "Setup nodes"
  import_playbook: "gitlab_cluster/main.yml"
- name: "Setup nailloux cluster"
  import_playbook: "nailloux_cluster/main.yml"